import type { Question, Handlungsfeld } from "./types";

import { importedQuestions } from "./questions-imported";

const baseQuestions: Question[] = [
  // ═══════════════════════════════════════════════════════════════════════════
  // HANDLUNGSFELD 1 – Ausbildungsvoraussetzungen prüfen & planen
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: "hf1-001",
    handlungsfeld: "HF1",
    topic: "Jugendarbeitsschutz",
    type: "mc",
    source: "Hdf1 Zusammenfassende Übung, Frage 1",
    difficulty: 2,
    prompt: "Wann ist die Bescheinigung über ärztliche Erstuntersuchung nach dem Jugendarbeitsschutzgesetz der Handwerkskammer vorzulegen?",
    options: [
      "Zusammen mit dem Berufsausbildungsvertrag während der Probezeit",
      "Zusammen mit dem Berufsausbildungsvertrag vor Beginn der Berufsausbildung",
      "Zusammen mit dem Berufsausbildungsvertrag nach Ablauf der Probezeit",
      "Es ist nicht vorgeschrieben, die ärztliche Bescheinigung der Handwerkskammer vorzulegen.",
      "Die ärztliche Bescheinigung ist nicht vorzulegen; es genügt der Vermerk im Berufsausbildungsvertrag.",
    ],
    correctAnswer: 1,
    explanation: "Die ärztliche Erstuntersuchung muss VOR Beginn der Ausbildung vorliegen und zusammen mit dem Vertrag bei der HWK eingereicht werden. Ohne diese Bescheinigung darf die Ausbildung eines Jugendlichen nicht beginnen (§ 32 JArbSchG).",
    hint: "Denke daran: Die Untersuchung soll sicherstellen, dass der Jugendliche für die Ausbildung geeignet ist – das muss natürlich VOR dem Start geklärt sein.",
    tags: ["JArbSchG", "§32", "Erstuntersuchung", "HWK"],
  },
  {
    id: "hf1-002",
    handlungsfeld: "HF1",
    topic: "Ausbildungsordnung",
    type: "mc",
    source: "Hdf1 Zusammenfassende Übung, Frage 2",
    difficulty: 1,
    prompt: "Sie bilden zum ersten Mal einen Lehrling in einem anerkannten Ausbildungsberuf aus. Die wichtigste Vorgabe, nach der Sie grundsätzlich und inhaltlich verbindlich ausbilden müssen, ist",
    options: [
      "die Ausbildungsordnung",
      "die Ausbildereignungsverordnung",
      "die Meisterprüfungsordnung",
      "die Schulordnung der Berufsschule",
      "die Ausbildungsrichtlinie der Agentur für Arbeit.",
    ],
    correctAnswer: 0,
    explanation: "Die Ausbildungsordnung (AO) ist die zentrale rechtliche Grundlage für die betriebliche Ausbildung. Sie enthält: Bezeichnung des Berufs, Ausbildungsdauer, Ausbildungsberufsbild, Ausbildungsrahmenplan und Prüfungsanforderungen. Die AO wird vom zuständigen Bundesministerium erlassen.",
    hint: "Welches Dokument regelt bundesweit einheitlich WAS in einer Ausbildung vermittelt werden muss?",
    tags: ["Ausbildungsordnung", "BBiG", "§4"],
  },
  {
    id: "hf1-003",
    handlungsfeld: "HF1",
    topic: "Jugendarbeitsschutz",
    type: "mc",
    source: "Hdf1 Zusammenfassende Übung, Frage 3",
    difficulty: 2,
    prompt: "Die Ruhepausen für einen Jugendlichen betragen bei einer Arbeitszeit von 8 Stunden am Tag mindestens",
    options: [
      "30 Minuten",
      "45 Minuten",
      "60 Minuten",
      "75 Minuten",
      "45 + 30 Minuten",
    ],
    correctAnswer: 2,
    explanation: "Bei mehr als 6 Stunden Arbeitszeit haben Jugendliche Anspruch auf 60 Minuten Pause (§ 11 JArbSchG). Diese kann in 2x 30 Min aufgeteilt werden. Erwachsene haben bei >6h nur 30 Min und bei >9h 45 Min Pause.",
    hint: "Jugendliche haben längere Pausen als Erwachsene! Bei über 6 Stunden Arbeitszeit... wie viele Minuten?",
    tags: ["JArbSchG", "§11", "Ruhepausen", "Arbeitszeit"],
  },
  {
    id: "hf1-004",
    handlungsfeld: "HF1",
    topic: "Schlüsselqualifikationen",
    type: "mc",
    source: "Hdf1 Zusammenfassende Übung, Frage 4",
    difficulty: 2,
    prompt: "Welche Aussage trifft in Bezug auf Schlüsselqualifikationen zu?",
    options: [
      "Unter Schlüsselqualifikationen versteht man alle Fertigkeiten, Kenntnisse und Fähigkeiten, die ausschließlich mit dem eigentlichen Beruf zusammenhängen.",
      "Schlüsselqualifikationen beziehen sich auch auf Fähigkeiten, die zur Bewältigung zukünftiger Anforderungen des Berufslebens geeignet sind.",
      "Schlüsselqualifikationen werden erst in der Meisterprüfung vermittelt.",
      "Unter Schlüsselqualifikationen versteht man die Kontrolle von Mitarbeitern.",
      "Schlüsselqualifikationen werden nur in kaufmännischen Berufsausbildungen vermittelt.",
    ],
    correctAnswer: 1,
    explanation: "Schlüsselqualifikationen sind berufsübergreifende Fähigkeiten wie Teamfähigkeit, Problemlösungskompetenz, Kommunikation – sie helfen, sich an wechselnde Anforderungen im Berufsleben anzupassen.",
    hint: "Schlüsselqualifikationen öffnen Türen zu vielen Bereichen – sie sind NICHT auf einen bestimmten Beruf beschränkt.",
    tags: ["Schlüsselqualifikationen", "Kompetenz"],
  },
  {
    id: "hf1-005",
    handlungsfeld: "HF1",
    topic: "Kammer",
    type: "mc",
    source: "Hdf1 Zusammenfassende Übung, Frage 5",
    difficulty: 2,
    prompt: "Wer hat darüber zu wachen, dass die persönliche und fachliche Eignung zur Einstellung und Ausbildung von Jugendlichen vorliegt?",
    options: [
      "Die Berufsschule",
      "Das Gewerbeaufsichtsamt",
      "Die Agentur für Arbeit",
      "Die Handwerkskammer",
      "Das Bundesinstitut für Berufsbildung",
    ],
    correctAnswer: 3,
    explanation: "Die Handwerkskammer (HWK) ist die zuständige Stelle für die Überwachung der Berufsausbildung im Handwerk. Sie prüft persönliche und fachliche Eignung, Eignung der Ausbildungsstätte und führt die Lehrlingsrolle (§ 41a HwO).",
    hint: "Welche Institution ist im Handwerk für ALLES rund um die Ausbildung zuständig?",
    tags: ["HWK", "Handwerkskammer", "Eignung", "§41a HwO"],
  },
  {
    id: "hf1-006",
    handlungsfeld: "HF1",
    topic: "Eignung",
    type: "mc",
    source: "Hdf1 Zusammenfassende Übung, Frage 6",
    difficulty: 3,
    context: "Ein Betrieb, der bisher keine Lehrlinge ausgebildet hat, plant für das nächste Jahr, drei Auszubildende einzustellen. Aufgrund der gegebenen Betriebsgröße kann der Betriebsinhaber die Ausbildung nicht selbst durchführen.",
    prompt: "Wie kann er das Problem lösen?",
    options: [
      "Eine Person mit bestandener Ausbildereignungsprüfung beschäftigen.",
      "Einen Ausbilder bestellen, der persönlich und fachlich geeignet ist und die Ausbildungsinhalte unmittelbar, verantwortlich und in wesentlichem Umfang vermittelt.",
      "Einen Gesellen mit Gesellenprüfung im Betrieb mit der gesamten Ausbildung beauftragen.",
      "Einen Fachlehrer der Berufsschule mit der Überwachung beauftragen.",
      "Den Lehrlingswart der Innung mitverantwortlich einbeziehen.",
    ],
    correctAnswer: 1,
    explanation: "Der bestellte Ausbilder muss persönlich und fachlich geeignet sein UND die Ausbildungsinhalte unmittelbar, verantwortlich und in wesentlichem Umfang selbst vermitteln. Nur die AEVO-Prüfung reicht nicht – auch die fachliche Qualifikation muss stimmen.",
    hint: "Drei Schlüsselwörter: unmittelbar, verantwortlich, wesentlicher Umfang.",
    tags: ["Ausbilder", "Eignung", "§28 HwO"],
  },
  {
    id: "hf1-007",
    handlungsfeld: "HF1",
    topic: "Jugendarbeitsschutz",
    type: "mc",
    source: "Hdf1 Zusammenfassende Übung, Frage 7",
    difficulty: 3,
    context: "Ein Betrieb beschäftigt einen Auszubildenden, der zu Beginn des Kalenderjahres noch nicht 18 Jahre alt ist.",
    prompt: "Wie hoch ist der gesetzliche Mindesturlaubsanspruch für das laufende Jahr?",
    options: [
      "15 Werktage",
      "18 Werktage",
      "25 Werktage",
      "30 Werktage",
      "35 Werktage",
    ],
    correctAnswer: 2,
    explanation: "Jugendliche unter 18 Jahren haben Anspruch auf 25 Werktage Urlaub (§ 19 JArbSchG). Unter 17: 30 Werktage, unter 16: noch nicht prüfungsrelevant. Erwachsene: mind. 24 Werktage (BUrlG).",
    hint: "Die Altersgruppe 'noch nicht 18' hat einen Urlaubsanspruch zwischen dem für unter-16 und dem für Erwachsene.",
    tags: ["JArbSchG", "§19", "Urlaub"],
  },
  {
    id: "hf1-008",
    handlungsfeld: "HF1",
    topic: "Ausbilderrolle",
    type: "mc",
    source: "Hdf1 Zusammenfassende Übung, Frage 8",
    difficulty: 3,
    prompt: "Worauf erstreckt sich die zentrale Überwachungsaufgabe des Ausbilders?",
    options: [
      "Auf die Einhaltung von BBiG und JArbSchG.",
      "Auf die Anforderungen der HWK und Innung.",
      "Auf die Teilnahme an ÜLU und Berufsschulunterricht.",
      "Auf die Anmeldung zur Zwischen- und Gesellenprüfung.",
      "Auf die Einhaltung der Ziele des gesamten Ausbildungsprozesses nach Ausbildungsplan sowie Planung und Steuerung.",
    ],
    correctAnswer: 4,
    explanation: "Die zentrale Aufgabe des Ausbilders ist die Sicherstellung, dass die Ausbildungsziele nach dem Ausbildungsplan erreicht werden. Alle anderen Punkte sind wichtig, aber nachgeordnet.",
    hint: "Was ist das ÜBERGEORDNETE Ziel eines Ausbilders? Gesetze einhalten ist wichtig, aber nicht die ZENTRALE Aufgabe.",
    tags: ["Ausbilder", "Überwachung", "Ausbildungsplan"],
  },
  {
    id: "hf1-009",
    handlungsfeld: "HF1",
    topic: "Jugendarbeitsschutz",
    type: "mc",
    source: "Hdf1 Zusammenfassende Übung, Frage 11",
    difficulty: 2,
    prompt: "Die höchstzulässige tägliche Arbeitszeit für jugendliche Auszubildende beträgt nach dem JArbSchG",
    options: [
      "8½ Stunden",
      "8 Stunden",
      "9 Stunden",
      "9½ Stunden",
      "10 Stunden",
    ],
    correctAnswer: 0,
    explanation: "Die HÖCHSTZULÄSSIGE tägliche Arbeitszeit beträgt 8½ Stunden (§ 8 Abs. 2a/2b JArbSchG). Das ist die Ausgleichsregelung: Wenn an einem anderen Tag kürzer gearbeitet wird, dürfen Jugendliche an einzelnen Tagen bis zu 8½ Stunden arbeiten. Der Grundsatz (§8 Abs. 1) sind zwar 8 Stunden/Tag und 40 Stunden/Woche – aber gefragt ist hier das MAXIMUM, und das ist 8½.",
    hint: "Gefragt ist die HÖCHSTZULÄSSIGE – nicht die übliche. Es gibt eine Ausgleichsregelung die mehr erlaubt.",
    tags: ["JArbSchG", "§8", "Arbeitszeit", "Ausgleichsregelung"],
  },
  {
    id: "hf1-010",
    handlungsfeld: "HF1",
    topic: "Berufsbildungsgesetz",
    type: "mc",
    source: "Hdf1 Zusammenfassende Übung, Frage 14",
    difficulty: 2,
    prompt: "Nach dem BBiG umfasst Berufsbildung bestimmte Bereiche. Welcher gehört NICHT dazu?",
    options: [
      "Berufsausbildungsvorbereitung",
      "Berufsausbildung",
      "Berufliche Fortbildung",
      "Berufliche Umschulung",
      "Hochschulzugangsregelung für beruflich Qualifizierte",
    ],
    correctAnswer: 4,
    explanation: "Die 4 Bereiche der Berufsbildung nach BBiG §1: 1) Berufsausbildungsvorbereitung, 2) Berufsausbildung, 3) Berufliche Fortbildung, 4) Berufliche Umschulung. Die Hochschulzugangsregelung ist NICHT Teil des BBiG.",
    hint: "Merke dir die 4 Säulen: Vorbereitung – Ausbildung – Fortbildung – Umschulung. Alles was darüber hinausgeht, ist nicht Teil des BBiG.",
    tags: ["BBiG", "§1", "Berufsbildung"],
  },
  {
    id: "hf1-011",
    handlungsfeld: "HF1",
    topic: "Jugendarbeitsschutz",
    type: "mc",
    source: "Hdf1 Zusammenfassende Übung, Frage 15",
    difficulty: 2,
    prompt: "Die ärztliche Nachuntersuchung nach dem Jugendarbeitsschutzgesetz muss spätestens erfolgen",
    options: [
      "vor Ablauf der Probezeit",
      "nach Ablauf der Probezeit",
      "ein Jahr nach Aufnahme der ersten Beschäftigung",
      "auf Verlangen des Arbeitgebers",
      "auf Verlangen des gesetzlichen Vertreters",
    ],
    correctAnswer: 2,
    explanation: "Die Nachuntersuchung muss spätestens 1 Jahr nach Aufnahme der ersten Beschäftigung erfolgen (§ 33 JArbSchG). Der Arbeitgeber muss den Jugendlichen darauf hinweisen.",
    hint: "Es geht um einen festen Zeitrahmen nach der ERSTEN Beschäftigung – wann läuft das Intervall ab?",
    tags: ["JArbSchG", "§33", "Nachuntersuchung"],
  },
  {
    id: "hf1-012",
    handlungsfeld: "HF1",
    topic: "Kammer",
    type: "mc",
    source: "Hdf1 Zusammenfassende Übung, Frage 16",
    difficulty: 3,
    prompt: "Wer führt das Verzeichnis der anerkannten Ausbildungsberufe?",
    options: [
      "Das Bundesinstitut für Berufsbildung",
      "Die IHK bzw. die Handwerkskammer",
      "Die Berufsschule",
      "Die Bundesagentur für Arbeit",
      "Das Amt für Ausbildungsförderung",
    ],
    correctAnswer: 0,
    explanation: "Das Bundesinstitut für Berufsbildung (BIBB) führt das Verzeichnis aller anerkannten Ausbildungsberufe in Deutschland. Die HWK/IHK führt die Lehrlingsrolle (Verzeichnis der Ausbildungsverhältnisse), nicht das Berufsverzeichnis.",
    hint: "Nicht die Kammer, nicht die Schule – es gibt eine Bundeseinrichtung die speziell für Berufsbildung zuständig ist.",
    tags: ["BIBB", "Ausbildungsberufe", "Verzeichnis"],
  },
  {
    id: "hf1-013",
    handlungsfeld: "HF1",
    topic: "Berufsbildungsausschuss",
    type: "mc",
    source: "Hdf1 Zusammenfassende Übung, Frage 17",
    difficulty: 3,
    prompt: "Wie setzt sich der Berufsbildungsausschuss bei der HWK zusammen?",
    options: [
      "Präsident und Vizepräsident der Handwerkskammer",
      "Sechs Arbeitgebervertreter",
      "Sechs Arbeitgebervertreter, sechs Arbeitnehmervertreter",
      "Sechs AG-Vertreter, sechs AN-Vertreter und der Geschäftsführer der Agentur für Arbeit",
      "Sechs AG-Vertreter, sechs AN-Vertreter und sechs Lehrer",
    ],
    correctAnswer: 4,
    explanation: "Der Berufsbildungsausschuss besteht aus 6 Arbeitgebern + 6 Arbeitnehmern + 6 Lehrern = 18 Mitglieder. Die Lehrer haben nur beratende Stimme, AG und AN haben Stimmrecht.",
    hint: "Drei Gruppen zu je 6 Personen: Arbeitgeber + Arbeitnehmer + ...wer noch?",
    tags: ["Berufsbildungsausschuss", "HWK", "§77 BBiG"],
  },
  {
    id: "hf1-014",
    handlungsfeld: "HF1",
    topic: "Ausbildungsordnung",
    type: "mc",
    source: "Hdf1 Zusammenfassende Übung, Frage 22",
    difficulty: 2,
    prompt: "Was wird in einer Ausbildungsordnung geregelt?",
    options: [
      "Ausbildungsvergütung",
      "Zusammensetzung des Prüfungsausschusses",
      "Ausbildungsdauer",
      "Lehrplan der Berufsschule",
      "Urlaubsanspruch",
    ],
    correctAnswer: 2,
    explanation: "Die Ausbildungsordnung regelt nach §5 BBiG: 1) Bezeichnung des Berufs, 2) Ausbildungsdauer, 3) Ausbildungsberufsbild, 4) Ausbildungsrahmenplan, 5) Prüfungsanforderungen. Vergütung und Urlaub werden im Vertrag bzw. Tarifvertrag geregelt.",
    hint: "Die 5 Mindestinhalte der AO – die Dauer ist eine davon.",
    tags: ["Ausbildungsordnung", "§5 BBiG"],
  },
  {
    id: "hf1-015",
    handlungsfeld: "HF1",
    topic: "Eignung",
    type: "mc",
    source: "Hdf1 Zusammenfassende Übung, Frage 26",
    difficulty: 3,
    context: "Aufgrund der hohen Spezialisierung kann Ihr Betrieb nicht alle Kenntnisse und Fertigkeiten vermitteln.",
    prompt: "Welche Folge hat dies für den Wunsch auszubilden?",
    options: [
      "Persönliche Eignung nicht gegeben, Ausbildung nicht möglich.",
      "Betriebliche Eignung nicht gegeben, Ausbildung nicht möglich.",
      "Fachliche Eignung nicht gegeben, Ausbildung nicht möglich.",
      "Ausbildung nur möglich, wenn Berufsschule fehlende Inhalte ausgleicht.",
      "Ausbildung grundsätzlich möglich, z.B. durch Ausbildung im Verbund mit anderen Betrieben.",
    ],
    correctAnswer: 4,
    explanation: "Wenn ein Betrieb nicht alle Inhalte vermitteln kann, ist eine Verbundausbildung möglich. Dabei kooperieren mehrere Betriebe, um alle Ausbildungsinhalte abzudecken. Das ist gesetzlich vorgesehen und gängige Praxis.",
    hint: "Es gibt eine Lösung, die mehrere Betriebe zusammenbringt...",
    tags: ["Verbundausbildung", "betriebliche Eignung"],
  },
  {
    id: "hf1-016",
    handlungsfeld: "HF1",
    topic: "Eignung",
    type: "mc",
    source: "Hdf1 Zusammenfassende Übung, Frage 30",
    difficulty: 3,
    prompt: "Eine rechtliche Voraussetzung zum Einstellen von Lehrlingen ist die persönliche Eignung. Welche Aussage trifft zu?",
    options: [
      "Die persönliche Eignung wird mit der Meisterprüfung erworben.",
      "Die persönliche Eignung ist nur gegeben, wenn die Räumlichkeiten geeignet sind.",
      "Für nichthandwerkliche Berufe ist keine persönliche Eignung notwendig.",
      "Grundsätzlich ist jeder Betriebsinhaber persönlich geeignet, sofern keine Ausschlussgründe vorliegen.",
      "Die persönliche Eignung erlischt, wenn man 5 Jahre keinen Lehrling einstellt.",
    ],
    correctAnswer: 3,
    explanation: "Die persönliche Eignung liegt grundsätzlich vor, AUSSER es liegen Ausschlussgründe vor (§ 22a HwO): z.B. schwere Verstöße gegen BBiG/JArbSchG, Straftaten gegen Jugendliche, Entzug der Ausbildungsberechtigung. Es ist also eine 'negative' Prüfung.",
    hint: "Bei der persönlichen Eignung geht es nicht um Qualifikation, sondern um Ausschlussgründe.",
    tags: ["persönliche Eignung", "§22a HwO"],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // HANDLUNGSFELD 2 – Ausbildung vorbereiten
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: "hf2-001",
    handlungsfeld: "HF2",
    topic: "Ausbildungsrecht",
    type: "mc",
    source: "Übungsaufgaben al.pdf",
    difficulty: 2,
    context: "Ihr Lehrling möchte gerne einen Teil seiner Berufsausbildung im Ausland verbringen.",
    prompt: "Welche Aussage trifft hierfür zu?",
    options: [
      "Ein Auslandsaufenthalt ist nach BBiG nicht möglich.",
      "Nur mit fließender Landessprache genehmigt die HWK den Aufenthalt.",
      "Nur für volljährige Lehrlinge möglich.",
      "Ein Auslandsaufenthalt ist möglich und kann bis zu einem Viertel der regulären Ausbildungszeit dauern.",
      "Der Lehrling hat einen Rechtsanspruch auch ohne Zustimmung des Betriebs.",
    ],
    correctAnswer: 3,
    explanation: "Nach §2 Abs. 3 BBiG können Teile der Ausbildung im Ausland durchgeführt werden, bis zu einem Viertel der Ausbildungsdauer. Voraussetzung: Es dient dem Ausbildungsziel und Betrieb stimmt zu.",
    hint: "Es gibt eine Maximaldauer, die als Bruchteil der Gesamtausbildung definiert ist...",
    tags: ["BBiG", "§2", "Auslandsaufenthalt"],
  },
  {
    id: "hf2-002",
    handlungsfeld: "HF2",
    topic: "Kündigung",
    type: "mc",
    source: "Übungsaufgaben al.pdf",
    difficulty: 2,
    context: "Ein Lehrling kündigt schriftlich, weil er die Berufsausbildung aufgeben will.",
    prompt: "Ist diese Kündigung in der erfolgten Art und Weise zulässig?",
    options: [
      "Ja, für die Aufgabe der Ausbildung gibt es keine Kündigungsfrist.",
      "Nein, Kündigungsfrist von 4 Wochen einzuhalten.",
      "Nein, Kündigungsfrist von 3 Wochen.",
      "Nein, Kündigungsfrist von 2 Wochen.",
      "Nein, Kündigungsfrist von 1 Woche.",
    ],
    correctAnswer: 1,
    explanation: "Nach der Probezeit kann der Azubi mit einer Kündigungsfrist von 4 Wochen kündigen, wenn er die Berufsausbildung aufgeben oder sich für eine andere Berufstätigkeit ausbilden lassen will (§ 22 Abs. 2 BBiG).",
    hint: "Die Kündigungsfrist bei Aufgabe der Ausbildung ist genau einen Monat minus 2 Tage.",
    tags: ["Kündigung", "§22 BBiG", "4 Wochen"],
  },
  {
    id: "hf2-003",
    handlungsfeld: "HF2",
    topic: "Ausbildungsrecht",
    type: "mc",
    source: "Übungsaufgaben al.pdf",
    difficulty: 2,
    context: "Ein Bewerber möchte seine Berufsausbildung in Teilzeit durchführen, da er einen pflegebedürftigen Angehörigen betreut.",
    prompt: "Welche Aussage trifft zu?",
    options: [
      "Nein, Ausbildung kann nur in Vollzeit durchgeführt werden.",
      "Ja, in diesem Fall ist eine Teilzeitausbildung möglich.",
      "Nein, Teilzeit nur für alleinerziehende Mütter.",
      "Nein, nur für Frauen.",
      "Nein, berufliche Handlungskompetenz kann in Teilzeit nicht vermittelt werden.",
    ],
    correctAnswer: 1,
    explanation: "Seit der BBiG-Novelle 2020 ist Teilzeitausbildung für ALLE möglich (§7a BBiG), nicht nur bei besonderen Gründen. Die Gesamtdauer verlängert sich entsprechend, maximal auf das 1,5-fache.",
    hint: "Das BBiG wurde 2020 modernisiert – Teilzeit ist jetzt viel breiter möglich als früher.",
    tags: ["Teilzeitausbildung", "§7a BBiG"],
  },
  {
    id: "hf2-004",
    handlungsfeld: "HF2",
    topic: "Probezeit",
    type: "mc",
    source: "MC Übungsfragen Bartmann, Frage 3",
    difficulty: 2,
    prompt: "Was trifft bei der Auswertung der Probezeit NICHT zu?",
    options: [
      "Die Probezeit dient dazu, die Eignung des Lehrlings einzuschätzen.",
      "Erfahrungen können für weitere Fördermaßnahmen genutzt werden.",
      "Der Ausbilder beobachtet Verhalten und Leistung besonders aufmerksam.",
      "Weibliche Auszubildende sollen grundsätzlich anders beurteilt werden.",
      "Die Probezeit liefert Grundlage für weitere Ausbildungsschritte.",
    ],
    correctAnswer: 3,
    explanation: "Eine unterschiedliche Beurteilung nach Geschlecht verstößt gegen das AGG (Allgemeines Gleichbehandlungsgesetz). Alle Azubis werden nach den gleichen Kriterien beurteilt.",
    hint: "Eines der Antworten verstößt gegen ein wichtiges Gleichbehandlungsgesetz...",
    tags: ["Probezeit", "AGG", "Gleichbehandlung"],
  },
  {
    id: "hf2-005",
    handlungsfeld: "HF2",
    topic: "Jugendarbeitsschutz",
    type: "mc",
    source: "MC Übungsfragen Bartmann, Frage 4",
    difficulty: 1,
    prompt: "In welchem Gesetz ist der Schutz Jugendlicher bei Nachtarbeit geregelt?",
    options: [
      "Im Jugendarbeitsschutzgesetz.",
      "Im Berufsbildungsgesetz.",
      "Im Arbeitszeitgesetz.",
      "Im Bürgerlichen Gesetzbuch.",
      "Im Mutterschutzgesetz.",
    ],
    correctAnswer: 0,
    explanation: "Das JArbSchG regelt alle Arbeitszeitbestimmungen für Jugendliche, einschließlich des Verbots von Nachtarbeit (§ 14 JArbSchG). Das ArbZG gilt für Erwachsene.",
    hint: "Der Name des Gesetzes sagt es schon – Jugend + Arbeit + Schutz.",
    tags: ["JArbSchG", "§14", "Nachtarbeit"],
  },
  {
    id: "hf2-006",
    handlungsfeld: "HF2",
    topic: "Ausbildungsvertrag",
    type: "mc",
    source: "Übungsaufgaben al.pdf",
    difficulty: 3,
    prompt: "Welchen Vertrag schließt ein Betriebsinhaber für eine Einstiegsqualifizierung in der Regel ab?",
    options: [
      "Einen unbefristeten Arbeitsvertrag.",
      "Einen Berufsausbildungsvertrag.",
      "Einen Einstiegsqualifizierungsvertrag (Praktikantenvertrag).",
      "Einen Vorvertrag zu einem Berufsausbildungsvertrag.",
      "Einen Leiharbeitsvertrag.",
    ],
    correctAnswer: 2,
    explanation: "Die Einstiegsqualifizierung (EQ) ist ein betriebliches Langzeitpraktikum (6-12 Monate), das als Brücke in die Ausbildung dient. Es wird ein Praktikantenvertrag geschlossen, gefördert durch die Agentur für Arbeit.",
    hint: "Die EQ ist kein Ausbildungsverhältnis, sondern ein besonderes Praktikum.",
    tags: ["Einstiegsqualifizierung", "EQ", "Praktikum"],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // HANDLUNGSFELD 3 – Ausbildung durchführen
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: "hf3-001",
    handlungsfeld: "HF3",
    topic: "Sinneswahrnehmung",
    type: "mc",
    source: "HF3 Wiesbaden, Frage 01",
    difficulty: 2,
    context: "Tischlermeister Volker Grünfeld plant, dem Auszubildenden die Augen zu verbinden und vier Holzsorten am Geruch erkennen zu lassen.",
    prompt: "Welche Art der Sinneswahrnehmung verlangt er von dem Auszubildenden?",
    options: [
      "kinästhetisch",
      "olfaktorisch",
      "gustatorisch",
      "auditiv",
    ],
    correctAnswer: 1,
    explanation: "Geruch = olfaktorische Wahrnehmung. Kinästhetisch = Bewegung/Körper, gustatorisch = Geschmack, auditiv = Hören, visuell = Sehen, haptisch/taktil = Tasten.",
    hint: "Es geht um die Nase – wie heißt das Fremdwort dafür?",
    tags: ["Sinneswahrnehmung", "olfaktorisch", "Didaktik"],
  },
  {
    id: "hf3-002",
    handlungsfeld: "HF3",
    topic: "Didaktische Prinzipien",
    type: "mc",
    source: "HF3 Wiesbaden, Frage 02",
    difficulty: 2,
    context: "Ihr Auszubildender hat Probleme mit der Mathematik, ist aber handwerklich geschickt. Sie geben ihm zusätzliche Hilfestellungen und knüpfen an seine Vorkenntnisse an.",
    prompt: "Welches didaktische Prinzip wenden Sie hauptsächlich an?",
    options: [
      "Orientierung an Lernzielen",
      "Handlungsorientierung/Aktivitätsförderung",
      "Individualisierung und Differenzierung",
      "Anschaulichkeit/Fasslichkeit",
    ],
    correctAnswer: 2,
    explanation: "Es wird gezielt auf die individuellen Stärken/Schwächen eingegangen und der Unterricht an die Person angepasst. Das ist das Prinzip der Individualisierung und Differenzierung.",
    hint: "Der Ausbilder passt seinen Unterricht an die EINZELNE Person an – ein bestimmtes didaktisches Prinzip.",
    tags: ["Didaktik", "Individualisierung", "Differenzierung"],
  },
  {
    id: "hf3-003",
    handlungsfeld: "HF3",
    topic: "Lernziele",
    type: "mc",
    source: "HF3 Wiesbaden, Frage 03",
    difficulty: 2,
    context: "Glasermeister zeigt seinem Auszubildenden, wie eine Glastür eingebaut wird. Der Azubi soll die Reihenfolge der Arbeitsschritte auswendig lernen.",
    prompt: "Zu welchem Lernzielbereich gehört das Lernziel?",
    options: [
      "kognitiv",
      "reproduktiv",
      "psychomotorisch",
      "affektiv",
    ],
    correctAnswer: 0,
    explanation: "'Auswendig lernen' = Wissen speichern = kognitiver Bereich. Psychomotorisch wäre das praktische Tun, affektiv betrifft Einstellungen/Werte. 'Reproduktiv' ist ein Lernzielniveau, kein Bereich.",
    hint: "Es geht ums WISSEN, nicht ums TUNS oder FÜHLENS – welcher Lernzielbereich ist das?",
    tags: ["Lernziele", "kognitiv", "Taxonomie"],
  },
  {
    id: "hf3-004",
    handlungsfeld: "HF3",
    topic: "Vollständige Handlung",
    type: "mc",
    source: "HF3 Wiesbaden, Frage 04",
    difficulty: 2,
    prompt: "Wie lautet die richtige Reihenfolge des Modells der vollständigen Handlung (6 Schritte)?",
    options: [
      "Informieren – Planen – Entscheiden – Durchführen – Kontrollieren – Bewerten",
      "Planen – Entscheiden – Informieren – Durchführen – Kontrollieren – Bewerten",
      "Bewerten – Planen – Informieren – Entscheiden – Durchführen – Kontrollieren",
      "Informieren – Planen – Bewerten – Entscheiden – Durchführen – Kontrollieren",
    ],
    correctAnswer: 0,
    explanation: "Merkhilfe: I-P-E-D-K-B – Informieren, Planen, Entscheiden, Durchführen, Kontrollieren, Bewerten. Die vollständige Handlung ist ein zentrales Konzept der handlungsorientierten Ausbildung.",
    hint: "Eselsbrücke: I-P-E-D-K-B. Was kommt zuerst – sich informieren oder planen?",
    tags: ["vollständige Handlung", "IPEDKB", "Handlungsorientierung"],
  },
  {
    id: "hf3-005",
    handlungsfeld: "HF3",
    topic: "Ausbildungsmethoden",
    type: "mc",
    source: "HF3 Wiesbaden, Frage 05",
    difficulty: 3,
    context: "Ihr Azubi ist seit einem Jahr im Betrieb. Sie möchten eine lernerzentrierte Methode anwenden, da er Vorwissen hat.",
    prompt: "Welche Ausbildungsmethode sollten Sie wählen?",
    options: [
      "Erarbeitende Unterweisungsmethode",
      "Vier-Stufen-Methode",
      "Lehrgespräch",
      "Lernauftrag",
    ],
    correctAnswer: 3,
    explanation: "Der Lernauftrag ist die lernerzentrierteste Methode – der Azubi erarbeitet sich den Inhalt selbstständig. Voraussetzung: Vorwissen und Erfahrung im Betrieb. Reihenfolge von ausbilder- zu lernerzentriert: Vier-Stufen → Lehrgespräch → Erarbeitend → Lernauftrag.",
    hint: "Welche Methode gibt dem Azubi die MEISTE Eigenverantwortung?",
    tags: ["Lernauftrag", "Methoden", "lernerzentriert"],
  },
  {
    id: "hf3-006",
    handlungsfeld: "HF3",
    topic: "Vier-Seiten-Modell",
    type: "mc",
    source: "HF3 Wiesbaden, Frage 07",
    difficulty: 3,
    context: "Handwerksmeisterin sagt zu ihrer Azubine: 'Die Frühstückspause ist in fünf Minuten vorbei!'",
    prompt: "Wie könnte die Azubine diesen Satz auf der Beziehungsebene verstehen?",
    options: [
      "'Sie will mich informieren, dass ich noch fünf Minuten Pause habe.'",
      "'Sie hat Angst, dass ich die Pause überziehe.'",
      "'Sie hält mich für zu blöd, selbst auf die Uhr zu sehen.'",
      "'Sie verlangt die unbedingte Einhaltung der Pausenzeiten.'",
    ],
    correctAnswer: 2,
    explanation: "Vier-Seiten-Modell (Schulz von Thun): Sachebene (A), Selbstoffenbarung (B), Beziehungsebene (C), Appell (D). Die Beziehungsebene sagt: 'Was hält der Sender vom Empfänger?' → C drückt aus: 'Du kannst das nicht allein.'",
    hint: "Die BEZIEHUNGSEBENE drückt aus, was der Sender vom Empfänger HÄLT. Welche Antwort zeigt das?",
    tags: ["Kommunikation", "Vier-Seiten-Modell", "Schulz von Thun"],
  },
  {
    id: "hf3-007",
    handlungsfeld: "HF3",
    topic: "Konfliktmanagement",
    type: "mc",
    source: "HF3 Wiesbaden, Frage 08",
    difficulty: 2,
    context: "Das Verhältnis zwischen Meister und Azubi ist stark belastet. Auch Ausbildungsberater und Lehrlingswart konnten nicht helfen.",
    prompt: "Welchen nächsten Schritt sollte der Meister unternehmen?",
    options: [
      "Ordentlich kündigen und Abfindung zahlen",
      "Unmittelbar einen Arbeitsgerichtsprozess anstreben",
      "Ein Schlichtungsverfahren beantragen",
      "Nichts tun und die Kündigung des Azubis abwarten",
    ],
    correctAnswer: 2,
    explanation: "Bei Streitigkeiten aus dem Ausbildungsverhältnis ist VOR dem Arbeitsgerichtsprozess ein Schlichtungsverfahren vor dem Schlichtungsausschuss der Kammer vorgeschrieben (§ 111 ArbGG). Das ist ein Muss-Schritt!",
    hint: "Bevor es vor Gericht geht, muss im Handwerk ein bestimmtes Verfahren durchlaufen werden...",
    tags: ["Schlichtung", "§111 ArbGG", "Konflikt"],
  },
  {
    id: "hf3-008",
    handlungsfeld: "HF3",
    topic: "Beurteilungsfehler",
    type: "mc",
    source: "HF3 Wiesbaden, Frage 09",
    difficulty: 3,
    context: "Friseurmeisterin bewertet beide Azubi-Leistungen mit 'befriedigend', obwohl es erkennbare Unterschiede gibt.",
    prompt: "Welchen subjektiven Beurteilungsfehler hat sie begangen?",
    options: [
      "Mildefehler",
      "Überstrahlungsfehler",
      "Fehler der Zentraltendenz",
      "Korrekturfehler",
    ],
    correctAnswer: 2,
    explanation: "Zentraltendenz = alles wird zur Mitte bewertet, extreme Noten werden vermieden. Mildefehler = zu gut, Überstrahlungsfehler (Halo) = ein Merkmal überstrahlt alles, Korrekturfehler = zu streng.",
    hint: "Die Bewertungen werden alle in die MITTE gezogen, statt die Unterschiede abzubilden.",
    tags: ["Beurteilungsfehler", "Zentraltendenz", "Bewertung"],
  },
  {
    id: "hf3-009",
    handlungsfeld: "HF3",
    topic: "Ausbildungsmethoden",
    type: "mc",
    source: "HF3 Wiesbaden, Frage 10",
    difficulty: 3,
    prompt: "Welchen wesentlichen Unterschied gibt es zwischen Vier-Stufen-Methode und erarbeitender Unterweisung?",
    options: [
      "Vier-Stufen für manuelle, erarbeitende für theoretische Tätigkeiten",
      "Die erarbeitende Methode bindet die Azubine früher aktiv ein und nähert sich selbstständiger Arbeitsweise",
      "Bei Vier-Stufen kann man besser motivieren",
      "Bei erarbeitender kontrolliert nur der Ausbilder",
    ],
    correctAnswer: 1,
    explanation: "Hauptunterschied: Bei der erarbeitenden Methode ist der Azubi von Anfang an aktiv beteiligt (fragend-entwickelnd), bei der Vier-Stufen-Methode zunächst passiv (Vormachen → Nachmachen).",
    hint: "Eine Methode beginnt mit ZEIGEN (passiv), die andere mit FRAGEN (aktiv) – welche ist aktiver?",
    tags: ["Vier-Stufen-Methode", "erarbeitende Unterweisung", "Methoden"],
  },
  {
    id: "hf3-010",
    handlungsfeld: "HF3",
    topic: "Ausbildungsmethoden",
    type: "mc",
    source: "HF3 Wiesbaden Block 2, Frage 08",
    difficulty: 2,
    context: "Schreinermeister möchte seinem Azubi den richtigen Umgang mit der Kreissäge vermitteln. Besonders wichtig ist der Gefahrenschutz.",
    prompt: "Welche Ausbildungsmethode sollte er wählen?",
    options: [
      "Rollenspiel",
      "Vier-Stufen-Methode",
      "Fachvortrag",
      "Lernauftrag",
    ],
    correctAnswer: 1,
    explanation: "Bei sicherheitsrelevanten praktischen Tätigkeiten (Kreissäge!) ist die Vier-Stufen-Methode die richtige Wahl: Vorbereiten – Vormachen – Nachmachen – Üben. Der Ausbilder kontrolliert jeden Schritt.",
    hint: "Bei GEFÄHRLICHEN Maschinen muss der Ausbilder JEDEN Schritt kontrollieren – welche Methode macht das?",
    tags: ["Vier-Stufen-Methode", "Sicherheit", "Kreissäge"],
  },
  {
    id: "hf3-011",
    handlungsfeld: "HF3",
    topic: "Frageformen",
    type: "mc",
    source: "HF3 Wiesbaden Block 2, Frage 09",
    difficulty: 2,
    context: "Handwerksmeister will ein Lehrgespräch führen und die Azubine möglichst aktiv einbinden.",
    prompt: "Welche Frageform sollte er zu Beginn nutzen?",
    options: [
      "Offene Fragen",
      "Geschlossene Fragen",
      "Alternativfragen",
      "Suggestivfragen",
    ],
    correctAnswer: 0,
    explanation: "Offene Fragen (W-Fragen) fordern zum Nachdenken und Sprechen auf. Geschlossene = Ja/Nein, Alternativ = vorgegebene Optionen, Suggestiv = legen die Antwort nahe.",
    hint: "Welche Fragen beginnen mit W-Wörtern (Warum, Wie, Was) und lassen den meisten Raum für eigene Gedanken?",
    tags: ["Frageformen", "offene Fragen", "Lehrgespräch"],
  },
  {
    id: "hf3-012",
    handlungsfeld: "HF3",
    topic: "Arbeitszergliederung",
    type: "mc",
    source: "HF3 Wiesbaden Block 2, Frage 10",
    difficulty: 3,
    prompt: "Welche Spaltenbezeichnungen hat die tabellarische Arbeitszergliederung in der richtigen Reihenfolge?",
    options: [
      "Was geschieht? – Wie geschieht es? – Warum geschieht es so?",
      "Was geschieht? – Wo geschieht es? – Wer vermittelt es?",
      "Wer vermittelt was? – Was geschieht? – Wann geschieht es?",
      "Wann geschieht was? – Wo geschieht es? – Warum geschieht es?",
    ],
    correctAnswer: 0,
    explanation: "Die klassische Arbeitszergliederung hat drei Spalten: WAS (Arbeitsschritt) – WIE (Ausführungshinweise) – WARUM (Begründung/Schlüsselstellen).",
    hint: "Drei einfache W-Fragen: Was, Wie, Warum.",
    tags: ["Arbeitszergliederung", "Unterweisung"],
  },
  {
    id: "hf3-013",
    handlungsfeld: "HF3",
    topic: "Lernzielniveau",
    type: "mc",
    source: "HF3 Wiesbaden Block 2, Frage 04",
    difficulty: 3,
    context: "Gerüstbaumeister zeigt, wie man ein Gerüst eines bestimmten Herstellers aufbaut. Der Azubi soll das Gelernte auch bei Gerüsten anderer Hersteller anwenden können.",
    prompt: "Auf welchem Lernzielniveau bewegt sich der Meister hier?",
    options: [
      "Reproduktion",
      "Reorganisation",
      "Transfer",
      "Schöpferische Leistung",
    ],
    correctAnswer: 2,
    explanation: "Transfer = Gelerntes auf neue, ähnliche Situationen übertragen. Reproduktion = nur wiederholen, Reorganisation = neu ordnen/darstellen, Schöpferische Leistung = etwas komplett Neues schaffen.",
    hint: "Das Gelernte wird auf eine ANDERE aber ähnliche Situation ÜBERTRAGEN – welches Niveau ist das?",
    tags: ["Lernzielniveau", "Transfer", "Taxonomie"],
  },
  {
    id: "hf3-014",
    handlungsfeld: "HF3",
    topic: "Konfliktgespräch",
    type: "mc",
    source: "HF3 Wiesbaden Block 2, Frage 13",
    difficulty: 3,
    prompt: "Wie strukturiert man ein Konfliktgespräch richtig (nach dem Einstieg)?",
    options: [
      "Ursachenanalyse – Lösungssuche – Beschreibungsphase – Umsetzung/Kontrolle",
      "Ursachenanalyse – Beschreibungsphase – Umsetzungsphase – Lösung/Kontrolle",
      "Beschreibungsphase – Ursachenanalyse – Lösungssuche – Umsetzung/Kontrolle",
      "Beschreibungsphase – Umsetzungsphase – Ursachenanalyse – Lösung/Kontrolle",
    ],
    correctAnswer: 2,
    explanation: "Erst beschreiben (Was ist passiert?) → dann Ursachen klären (Warum?) → dann Lösungen suchen → dann umsetzen und kontrollieren. Merke: B-U-L-U.",
    hint: "Zuerst muss man wissen WAS passiert ist, bevor man das WARUM klären kann.",
    tags: ["Konfliktgespräch", "Gesprächsführung"],
  },
  {
    id: "hf3-015",
    handlungsfeld: "HF3",
    topic: "Beurteilung",
    type: "mc",
    source: "HF3 Wiesbaden Block 2, Frage 14",
    difficulty: 3,
    context: "Meister gibt beiden Azubis getrennt die gleiche Aufgabe mit gleichen Bedingungen und hat eindeutige Bewertungskriterien festgelegt, die er den Azubis NICHT mitteilt.",
    prompt: "Welche Anforderung an Erfolgskontrollen hat er beachtet?",
    options: [
      "Objektivität",
      "Transparenz",
      "Normorientierung",
      "Handlungskompetenz",
    ],
    correctAnswer: 0,
    explanation: "Gleiche Bedingungen + eindeutige Kriterien = Objektivität. Transparenz wäre es, wenn er die Kriterien auch mitgeteilt hätte (hat er nicht!). Gütekriterien: Objektivität, Reliabilität, Validität.",
    hint: "Gleiche Bedingungen für alle, feste Kriterien – das sichert welches Gütekriterium?",
    tags: ["Beurteilung", "Objektivität", "Gütekriterien"],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // HANDLUNGSFELD 4 – Ausbildung abschließen
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: "hf4-001",
    handlungsfeld: "HF4",
    topic: "Gesellenprüfung",
    type: "mc",
    source: "Hdf1 Zusammenfassende Übung, Frage 33",
    difficulty: 3,
    prompt: "Welche Aussage trifft auf die ordnungsgemäße Zusammensetzung des Gesellenprüfungsausschusses zu?",
    options: [
      "Der Ausschuss wird beim Amtsgericht installiert.",
      "Er besteht aus mindestens drei Mitgliedern.",
      "Der Obermeister und Lehrlingswart können allein prüfen.",
      "Er besteht aus mindestens fünf Mitgliedern.",
      "Die Prüfung wird vor Mitarbeitern der HWK abgelegt.",
    ],
    correctAnswer: 1,
    explanation: "Der Gesellenprüfungsausschuss besteht aus mindestens 3 Mitgliedern: je ein Arbeitgeber, ein Arbeitnehmer und ein Berufsschullehrer. In der Praxis sind es oft mehr.",
    hint: "Es ist eine UNgerade Mindestzahl – AG, AN und ein Lehrer...",
    tags: ["Gesellenprüfung", "Prüfungsausschuss", "§34 HwO"],
  },
  {
    id: "hf4-002",
    handlungsfeld: "HF4",
    topic: "Umschulung",
    type: "mc",
    source: "Hdf1 Zusammenfassende Übung, Frage 23",
    difficulty: 2,
    prompt: "Welche Ziele hat die berufliche Umschulung?",
    options: [
      "Vertiefte Sprachkenntnisse in einer zweiten Fremdsprache.",
      "Vorbereitung auf die Meisterprüfung.",
      "Heranführung an eine Berufsausbildung in einem anerkannten Beruf.",
      "Vorbereitung auf die Ausbildereignungsprüfung.",
      "Die Befähigung zu einer anderen, bisher nicht erlernten Berufstätigkeit.",
    ],
    correctAnswer: 4,
    explanation: "Umschulung = Befähigung zu einem ANDEREN Beruf (§ 1 Abs. 5 BBiG). Nicht zu verwechseln mit Fortbildung (= Vertiefung im GLEICHEN Berufsfeld) oder Ausbildungsvorbereitung (= Heranführung an eine Erstausbildung).",
    hint: "Umschulung bedeutet einen NEUEN Beruf lernen, nicht den alten vertiefen.",
    tags: ["Umschulung", "§1 BBiG", "berufliche Bildung"],
  },
  {
    id: "hf4-003",
    handlungsfeld: "HF4",
    topic: "Aufstiegsfortbildung",
    type: "mc",
    source: "Hdf1 Zusammenfassende Übung, Frage 31",
    difficulty: 3,
    prompt: "Welche Rolle hat die höherqualifizierte Berufsausbildung (= Aufstiegsfortbildung) im Rahmen der Personalentwicklung?",
    options: [
      "Sie soll die Handlungsfähigkeit an geänderte Erfordernisse anpassen.",
      "Für Ausbildungsabsolventen gibt es keine Angebote.",
      "Man muss mindestens 25 Jahre alt sein.",
      "Bestes Beispiel sind Qualifizierungsbausteine.",
      "Sie soll es ermöglichen, die berufliche Handlungsfähigkeit für qualitativ höherwertige Berufstätigkeit zu erweitern und beruflich aufzusteigen.",
    ],
    correctAnswer: 4,
    explanation: "Die höherqualifizierende Berufsbildung (§ 1 Abs. 4 BBiG) ermöglicht den beruflichen Aufstieg. Beispiele: Meister, Techniker, Fachwirt. Option A beschreibt die Anpassungsfortbildung, nicht die Aufstiegsfortbildung.",
    hint: "Aufstiegsfortbildung = AUFSTEIGEN in der Karriere. Nicht verwechseln mit Anpassungsfortbildung!",
    tags: ["Aufstiegsfortbildung", "Personalentwicklung", "§1 BBiG"],
  },
  {
    id: "hf4-004",
    handlungsfeld: "HF4",
    topic: "Berufsschule",
    type: "mc",
    source: "Hdf1 Zusammenfassende Übung, Frage 32",
    difficulty: 2,
    prompt: "Ihr Lehrling besucht regelmäßig die Berufsschule. Was müssen Sie dabei beachten?",
    options: [
      "Die HWK kann eine Befreiung vom Unterricht erteilen.",
      "Der Unterricht ist freiwillig.",
      "Hat er nur 6 Unterrichtsstunden, muss er 2h im Betrieb nachholen.",
      "Die Beschäftigung vor einem vor 9 Uhr beginnenden Unterricht ist unzulässig.",
      "Das Schulgeld kann zur Hälfte von der Vergütung abgezogen werden.",
    ],
    correctAnswer: 3,
    explanation: "Jugendliche dürfen vor einem vor 9 Uhr beginnenden Unterricht nicht beschäftigt werden (§ 9 JArbSchG). Der Berufsschulunterricht ist Pflicht, ein Schultag mit >5 Unterrichtsstunden wird auf 8 Arbeitsstunden angerechnet.",
    hint: "Es gibt eine zeitliche Regelung für die BESCHÄFTIGUNG VOR dem Unterricht...",
    tags: ["Berufsschule", "§9 JArbSchG", "Freistellung"],
  },
  {
    id: "hf4-005",
    handlungsfeld: "HF4",
    topic: "Ausbildungsverantwortung",
    type: "mc",
    source: "Hdf1 Zusammenfassende Übung, Frage 27",
    difficulty: 2,
    prompt: "Wer hat die Verantwortung dafür, dass nach der Ausbildung die volle berufliche Handlungsfähigkeit vorhanden ist?",
    options: [
      "Die Berufsschule",
      "Die Handwerkskammer",
      "Der Ausbildungsbetrieb",
      "Die Innung",
      "Das BIBB",
    ],
    correctAnswer: 2,
    explanation: "Der Ausbildungsbetrieb (= der Ausbildende) trägt die Hauptverantwortung für die Vermittlung der beruflichen Handlungsfähigkeit. Die Berufsschule ergänzt mit theoretischem Wissen.",
    hint: "Wer hat den Vertrag mit dem Azubi geschlossen?",
    tags: ["Ausbildungsbetrieb", "Verantwortung", "Handlungsfähigkeit"],
  },
  {
    id: "hf4-006",
    handlungsfeld: "HF4",
    topic: "Ausbildender",
    type: "mc",
    source: "Hdf1 Zusammenfassende Übung, Frage 28",
    difficulty: 2,
    prompt: "Wer ist Ausbildender im Sinne des Gesetzes?",
    options: [
      "Wer im Auftrag des Ausbilders dem Lehrling Nachhilfe gibt.",
      "Wer die Ausbildung durchführt.",
      "Wer vom Betrieb für die Ausbildung beauftragt wird.",
      "Wer Lehrlinge einstellt.",
      "Ausbildender ist immer eine natürliche Person.",
    ],
    correctAnswer: 3,
    explanation: "Ausbildender = wer einstellt (§ 22 HwO) – das kann eine natürliche oder juristische Person sein (z.B. GmbH). Ausbilder = wer die Ausbildung tatsächlich durchführt. Ausbildungsbeauftragter = wer vom Ausbilder beauftragt wird.",
    hint: "Ausbildender ≠ Ausbilder. Der eine STELLT EIN, der andere BILDET AUS.",
    tags: ["Ausbildender", "Ausbilder", "§22 HwO", "Begriffe"],
  },
];

// Merge base + imported questions, deduplicating by ID
const seenIds = new Set<string>();
export const questions: Question[] = [];
for (const q of [...baseQuestions, ...importedQuestions]) {
  if (!seenIds.has(q.id)) {
    seenIds.add(q.id);
    questions.push(q);
  }
}

export function getQuestionById(id: string): Question | undefined {
  return questions.find((q) => q.id === id);
}

export function getQuestionsByHF(hf: Handlungsfeld): Question[] {
  return questions.filter((q) => q.handlungsfeld === hf);
}

export function getQuestionsByTopic(topic: string): Question[] {
  return questions.filter((q) => q.topic.toLowerCase().includes(topic.toLowerCase()));
}
